######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 20 15:58:56 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
SOURCES += RpiClient.cpp

HEADERS += Rpiclient.h
HEADERS += ByteBuffer.h
HEADERS += opcodes.h

CONFIG += console
CONFIG += debug
CONFIG += release

QT += network
QT -= gui
